# Generated by Django 6.0.4 on 2026-06-06 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=200)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('shipping_address', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'), models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['customer_email', 'status'], name='orders_orde_custome_66d5e2_idx'), models.Index(fields=['created_at', 'status'], name='orders_orde_created_49d91d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(blank=True, db_index=True, max_length=10)),
                ('color', models.CharField(blank=True, db_index=True, max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'), models.Index(fields=['size'], name='orders_orde_size_fee5ab_idx'), models.Index(fields=['color'], name='orders_orde_color_f6455c_idx'), models.Index(fields=['order', 'size'], name='orders_orde_order_i_0fc87f_idx'), models.Index(fields=['order', 'color'], name='orders_orde_order_i_662843_idx')],
            },
        ),
    ]
